import {COLS,ROWS,PIECES,TYPES,rotate,makeBag,collides,merge,clearLines,scoreFor,newPiece,emptyBoard} from './game-core.js';
import './styles.css';
const icons='/assets/icons/'; const avatar='/assets/avatars/';
const app=document.querySelector('#app');
app.innerHTML=`<header class="top"><div class="brand"><img src="/assets/design/de-tetris-logo.svg" alt="DE-TETRIS"/><span>STACK DATA · BUILD SOLUTIONS · CLEAR TOMORROW</span></div><div class="top-actions"><button id="sound" class="icon-btn" aria-label="Toggle sound">◉ SOUND</button><button id="contrast" class="icon-btn">◐ CONTRAST</button></div></header><main class="layout"><aside class="panel stats"><div class="eyebrow">PIPELINE STATUS</div><div class="status"><i></i> HEALTHY</div><div class="metric"><small>SCORE</small><strong id="score">0</strong></div><div class="metric"><small>LINES</small><strong id="lines">0</strong></div><div class="metric"><small>LEVEL</small><strong id="level">1</strong></div><div class="metric"><small>BEST</small><strong id="best">0</strong></div><div class="team"><div class="eyebrow">TEAM ROTATION</div><div class="faces">${['trevor','harry','shane','steve'].map(n=>`<img src="${avatar+n+'-tile.png'}" alt="${n}"/>`).join('')}</div><p id="toast">People + Data = Progress.</p></div></aside><section class="game"><div class="gamebar"><div><b id="mode">LIVE PIPELINE</b><span id="hint">7-bag randomisation · lock delay active</span></div><button id="pause" class="small-btn">Ⅱ PAUSE</button></div><div class="board-wrap"><canvas id="board" aria-label="Tetris playfield" tabindex="0"></canvas><div id="overlay" class="overlay hidden"><h2 id="overlay-title">PAUSED</h2><p id="overlay-copy">Pipeline paused.</p><button id="overlay-action" class="primary">RESUME</button></div></div><div class="mobile-stats"><span>SCORE <b id="mscore">0</b></span><span>LINES <b id="mlines">0</b></span><span>LVL <b id="mlevel">1</b></span></div><div class="touch"><button data-key="hold">HOLD</button><button data-key="left">←</button><button data-key="down">↓</button><button data-key="right">→</button><button data-key="rotate">↻</button><button data-key="drop" class="drop">DROP</button></div></section><aside class="panel queue"><div class="queue-head"><div><div class="eyebrow">HOLD</div><div id="hold" class="mini"></div></div><div><div class="eyebrow">NEXT STREAM</div><div id="next" class="next"></div></div></div><div class="controls"><div class="eyebrow">CONTROL MAP</div><p><kbd>←</kbd><kbd>→</kbd> MOVE <kbd>↓</kbd> SOFT DROP</p><p><kbd>SPACE</kbd> HARD DROP <kbd>↑</kbd> ROTATE</p><p><kbd>C</kbd> HOLD <kbd>P</kbd> PAUSE</p></div><div class="slogan">SAME DATA.<br/><em>BRIGHTER OUTCOMES.</em></div></aside></main><footer>DE-TETRIS <span>v1.0 · LOCAL HIGH SCORES</span><button id="install" class="install hidden">＋ INSTALL APP</button></footer>`;
const canvas=document.querySelector('#board'),ctx=canvas.getContext('2d');let board=emptyBoard(),bag=[],queue=[],current,hold=null,canHold=true,score=0,lines=0,level=1,combo=-1,dropCounter=0,last=0,running=true,over=false,sound=true,high=Number(localStorage.getItem('de-tetris-best')||0),audio;
const $=id=>document.querySelector(id); $('#best').textContent=high;
function refill(){while(queue.length<5){if(!bag.length)bag=makeBag();queue.push(bag.shift())}}
function spawn(){refill();current=newPiece(queue.shift());canHold=true;refill();if(collides(board,current)) endGame()}
function resize(){const max=Math.min(window.innerWidth<700?window.innerWidth-36:430,window.innerHeight*.63);canvas.width=max;canvas.height=max*2;canvas.style.width=max+'px';canvas.style.height=max*2+'px'}
function drawCell(x,y,size,val,ghost=false){if(y<0)return;ctx.globalAlpha=ghost?.2:1;ctx.fillStyle=val.color;ctx.shadowColor=val.color;ctx.shadowBlur=ghost?0:12;ctx.fillRect(x*size+1,y*size+1,size-2,size-2);ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,255,255,.35)';ctx.strokeRect(x*size+1,y*size+1,size-2,size-2);ctx.globalAlpha=1}
function render(){const s=canvas.width/COLS;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#08172b';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='rgba(39,216,255,.11)';ctx.lineWidth=1;for(let x=0;x<=COLS;x++){ctx.beginPath();ctx.moveTo(x*s,0);ctx.lineTo(x*s,canvas.height);ctx.stroke()}for(let y=0;y<=ROWS;y++){ctx.beginPath();ctx.moveTo(0,y*s);ctx.lineTo(canvas.width,y*s);ctx.stroke()}board.forEach((r,y)=>r.forEach((v,x)=>v&&drawCell(x,y,s,v)));if(current&&!over){let gy=current.y;while(!collides(board,{...current,y:gy+1}))gy++;current.shape.forEach((r,y)=>r.forEach((v,x)=>v&&drawCell(current.x+x,gy+y,s,current,true)));current.shape.forEach((r,y)=>r.forEach((v,x)=>v&&drawCell(current.x+x,current.y+y,s,current)))}updatePreviews()}
function updatePreviews(){const h=$('#hold');h.innerHTML=hold?piecePreview(hold):'<span class="empty">—</span>';$('#next').innerHTML=queue.slice(0,3).map(piecePreview).join('')}
function piecePreview(t){const p=PIECES[t];return `<div class="preview"><b>${t}</b><span class="tiles" style="--c:${p.color}">${p.shape.flatMap(r=>r.map(v=>v?'<i></i>':'<i class="off"></i>')).join('')}</span></div>`}
function move(dx){if(over||!running)return;if(!collides(board,{...current,x:current.x+dx})){current.x+=dx;beep(180)}}
function turn(dir=1){if(over||!running)return;const shape=rotate(current.shape,dir);for(const kick of [0,-1,1,-2,2]){const p={...current,shape,x:current.x+kick};if(!collides(board,p)){current.shape=shape;current.x+=kick;beep(300);return}}}
function holdPiece(){if(!canHold||over||!running)return;const t=current.type;if(hold){current=newPiece(hold);hold=t}else{hold=t;spawn()}canHold=false;render()}
function lock(){board=merge(board,current);const result=clearLines(board);board=result.board;if(result.count){lines+=result.count;combo++;score+=scoreFor(result.count,level,combo);if(result.count===4)toast('MERGE complete');else toast('Pipeline healthy');if(lines>=level*10){level++;toast(`Level ${level}: deploy velocity up`)}}else combo=-1;spawn();sync()}
function drop(hard=false){if(over||!running)return;if(hard){let d=0;while(!collides(board,{...current,y:current.y+1})){current.y++;d++}score+=d*2;lock();beep(80)}else if(!collides(board,{...current,y:current.y+1})){current.y++;score++;}else lock();sync()}
function sync(){$('#score').textContent=score;$('#lines').textContent=lines;$('#level').textContent=level;$('#mscore').textContent=score;$('#mlines').textContent=lines;$('#mlevel').textContent=level;render()}
function toast(text){$('#toast').textContent=text;$('#toast').classList.remove('flash');void $('#toast').offsetWidth;$('#toast').classList.add('flash')}
function endGame(){over=true;running=false;if(score>high){high=score;localStorage.setItem('de-tetris-best',high);$('#best').textContent=high}$('#overlay-title').textContent='PIPELINE OFFLINE';$('#overlay-copy').textContent=`Run complete · ${score.toLocaleString()} points · ${lines} lines`;$('#overlay-action').textContent='RESTART RUN';$('#overlay').classList.remove('hidden');toast('No schema drift detected');beep(70)}
function restart(){board=emptyBoard();bag=[];queue=[];hold=null;score=lines=0;level=1;combo=-1;over=false;running=true;$('#overlay').classList.add('hidden');spawn();sync()}
function pause(){if(over)return;running=!running;$('#pause').textContent=running?'Ⅱ PAUSE':'▶ RESUME';$('#overlay-title').textContent='PAUSED';$('#overlay-copy').textContent='Pipeline paused. Resume when ready.';$('#overlay-action').textContent='RESUME';$('#overlay').classList.toggle('hidden',running)}
function beep(freq){if(!sound)return;try{audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;o.type='sine';g.gain.value=.025;o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.045)}catch{}}
function loop(t=0){const dt=t-last;last=t;if(running&&!over){dropCounter+=dt;if(dropCounter>Math.max(90,800-(level-1)*65)){drop();dropCounter=0}}render();requestAnimationFrame(loop)}
addEventListener('resize',resize);addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowleft','arrowright','arrowdown',' ','arrowup','z','x','c','shift','p','escape','r'].includes(k))e.preventDefault();if(k==='arrowleft')move(-1);if(k==='arrowright')move(1);if(k==='arrowdown')drop();if(k===' ')drop(true);if(k==='arrowup'||k==='x')turn();if(k==='z')turn(-1);if(k==='c'||k==='shift')holdPiece();if(k==='p'||k==='escape')pause();if(k==='r')restart()});
$('#pause').onclick=pause;$('#overlay-action').onclick=()=>over?restart():pause();$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'◉ SOUND':'○ SOUND'};$('#contrast').onclick=()=>document.body.classList.toggle('contrast');document.querySelectorAll('.touch button').forEach(b=>b.onclick=()=>({left:()=>move(-1),right:()=>move(1),down:()=>drop(),rotate:()=>turn(),drop:()=>drop(true),hold:holdPiece}[b.dataset.key])());
let deferred;addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#install').classList.remove('hidden')});$('#install').onclick=async()=>{if(deferred){deferred.prompt();deferred=null;$('#install').classList.add('hidden')}};addEventListener('load',()=>navigator.serviceWorker?.register('/sw.js'));
resize();refill();spawn();sync();requestAnimationFrame(loop);
